### PR TITLE
prevent exception in client.transport getter

### PR DESCRIPTION
**Pull request by briangough**
### The kind of change this PR does introduce

* [x] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour

`this.manager.transports[this.id]` can be undefined,  so the `client.transport` getter triggers an exception `Uncaught TypeError: Cannot read property 'name' of undefined`

### New behaviour

The getter now returns undefined when `this.manager.transports[this.id]` is undefined.

### Other information (e.g. related issues)

Found in https://github.com/overleaf/real-time/pull/217

### CODE REVIEW

**Review by das7pad — APPROVED** [review]
Side note: I double checked that all the individual transports do not have another getter that could throw. They are all using constants as `.name`.

**Comment by briangough** [comment]
> Side note: I double checked that all the individual transports do not have another getter that could throw. They are all using constants as `.name`.

Thanks, I hadn't thought of that.

Incidentally, I was wondering how it is possible for the client to be connected  but not have a transport (since the exception happened in the `session.on('connection')` handler).

**Comment by das7pad** [comment]
> Incidentally, I was wondering how it is possible for the client to be connected but not have a transport (since the exception happened in the `session.on('connection')` handler).

The `session.on` handler fires after the session auth is done. There is a network call in-between socket.io fires and we pass it to the Router handler via SessionSockets.
https://github.com/overleaf/real-time/blob/1ea311a2f7a508b1d2dcf9c4b1256456624fdcbb/app/js/SessionSockets.js#L13-L33
Potentially we could add a check at the start of the Router handler and bail-out when seeing a disconnected client.

**Comment by briangough** [comment]
Ah, got it -- had forgotten about looking up the session in redis.

**Pull request merged**
